### ISSUE TITLE
Can you provide some test files?

### ISSUE THREAD

**Issue by huangjunying** [rachelselinar/ReGDS-Logic-Gate-Extraction#1]
Hello. Can you provide some test files, such the .sp files? So that the code can run correctly. Thanks.

**Comment by rachelselinar** [comment]
Hi HuangJunYing

Thank you for reaching out.
We cannot share the files used in the actual experiment due to NDA with
TSMC, however I can share some toy examples in the next few weeks.

Regards
Rachel

**Comment by huangjunying** [comment]
Thanks for replying.  Can you send me the toy examples now? 发自我的华为手机-------- 原始邮件 --------发件人： Rachel Selina Rajarathnam ***@***.***>日期： 2021年4月30日周五 凌晨1:08收件人： rachelselinar/ReGDS-Logic-Gate-Extraction ***@***.***>抄送： huangjunying ***@***.***>, Author ***@***.***>主    题： Re: [rachelselinar/ReGDS-Logic-Gate-Extraction] Can you provide some test files? (#1)

Hi HuangJunYing



Thank you for reaching out.

We cannot share the files used in the actual experiment due to NDA with

TSMC, however I can share some toy examples in the next few weeks.



Regards

Rachel



On Thu, Apr 29, 2021 at 12:49 AM huangjunying ***@***.***>

wrote:

**Comment by rachelselinar** [comment]
Included sample lib.sp file. Closing issue.
