### ISSUE TITLE
Question about available toy examples

### ISSUE THREAD

**Issue by microhumanis** [rachelselinar/ReGDS-Logic-Gate-Extraction#2]
Dear Rachel, 

I hope this question finds you well.

I would like to ask a question related to #1 issue. 

I am having a problem with running the code because of the lack of a test case.

I would be grateful if you could send me some toy examples to run the program correctly. 

Thank you very much for your time. I look forward to hearing from you. 

Best Regards,

Microhumanis

**Comment by rachelselinar** [comment]
Included sample library file lib.sp. You can create toy examples by using the lib.sp as reference. Closing issue.
